// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HTFaAga7421BVLyEad139_dBfxVuFIw',
    appId: '1:807301978978:web:07e2e7427ab355934eaa3b',
    messagingSenderId: '807301978978',
    projectId: 'chat-app-45898',
    authDomain: 'chat-app-45898.firebaseapp.com',
    storageBucket: 'chat-app-45898.firebasestorage.app',
    measurementId: 'G-4FQ94RM8BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9QuumB7OlDz5SDBIiwxP9jqSmHbuYirs',
    appId: '1:807301978978:android:fe1848cce5af20704eaa3b',
    messagingSenderId: '807301978978',
    projectId: 'chat-app-45898',
    storageBucket: 'chat-app-45898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACIs3uCkasFaVTDyt_Sq8hYFsSUqaZAfE',
    appId: '1:807301978978:ios:da908a18378a2d9c4eaa3b',
    messagingSenderId: '807301978978',
    projectId: 'chat-app-45898',
    storageBucket: 'chat-app-45898.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACIs3uCkasFaVTDyt_Sq8hYFsSUqaZAfE',
    appId: '1:807301978978:ios:da908a18378a2d9c4eaa3b',
    messagingSenderId: '807301978978',
    projectId: 'chat-app-45898',
    storageBucket: 'chat-app-45898.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2HTFaAga7421BVLyEad139_dBfxVuFIw',
    appId: '1:807301978978:web:1497b1fec4a865014eaa3b',
    messagingSenderId: '807301978978',
    projectId: 'chat-app-45898',
    authDomain: 'chat-app-45898.firebaseapp.com',
    storageBucket: 'chat-app-45898.firebasestorage.app',
    measurementId: 'G-ZQL2K0NYTV',
  );

}